version: "3.7"

services:
  aasp_web:
    build:
      context: .
      dockerfile: ./compose/aasp_web/Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:8000"
    restart: unless-stopped
    depends_on:
      - aasp_db
      - rabbitmq

  aasp_db:
    image: postgres:latest
    volumes:
      - aasp_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${AASP_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AASP_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AASP_POSTGRES_DB}

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/celery_worker/Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - rabbitmq

  judge0_server:
    image: judge0/judge0:latest
    volumes:
      - ./compose/judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    restart: unless-stopped
    depends_on:
      - judge0_db
      - judge0_redis

  judge0_worker:
    image: judge0/judge0:latest
    command: [ "./scripts/workers" ]
    volumes:
      - ./compose/judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    restart: unless-stopped
    depends_on:
      - judge0_db
      - judge0_redis

  judge0_db:
    image: postgres:13.0
    env_file: ./compose/judge0/judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped

  judge0_redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: ./compose/judge0/judge0.conf
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  aasp_postgres_data:
  postgres-data:
  redis-data:
