version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/celery_worker/Dockerfile
    network_mode: host
    volumes:
      - .:/app
    depends_on: 
      - rabbitmq
