version: "3.7"

services:
  aasp_db:
    image: postgres:latest
    env_file: ./config/.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - aasp_postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: ./config/aasp/Dockerfile
    entrypoint: celery -A aasp worker --loglevel=INFO
    environment:
      - POSTGRES_HOST=aasp_db
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - JUDGE0_URL=http://judge0_server:2358
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - rabbitmq

  judge0_server:
    image: chuachongyih/aasp-judge0:1.0.0
    volumes:
      - ./config/judge0/judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: unless-stopped
    depends_on:
      - judge0_db
      - judge0_redis

  judge0_worker:
    image: chuachongyih/aasp-judge0:1.0.0
    command: [ "./scripts/workers" ]
    volumes:
      - ./config/judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    restart: unless-stopped
    depends_on:
      - judge0_db
      - judge0_redis

  judge0_db:
    image: postgres:13.0
    env_file: ./config/judge0/judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped

  judge0_redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: ./config/judge0/judge0.conf
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  aasp_postgres_data:
  postgres-data:
  redis-data:
